apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
  labels:
    app: backend
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: ibmc-vpc-block-10iops-tier
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
