apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-oidc-cm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  OIDC_AUTH_URL: https://prepiam.ice.ibmcloud.com/v1.0/endpoint/default/authorize
  OIDC_DISCOVERY_ENDPOINT: https://prepiam.ice.ibmcloud.com/v1.0/endpoint/default/.well-known/openid-configuration
  OIDC_TOKEN_URL: https://prepiam.ice.ibmcloud.com/v1.0/endpoint/default/token
  OIDC_USERINFO_ENDPOINT: https://prepiam.ice.ibmcloud.com/v1.0/endpoint/default/userinfo