apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-watsonx-external-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: ibmcloud-secrets-store
    kind: ClusterSecretStore
  target:
    name: backend-watsonx-secret
  data:
  - secretKey: WATSONX_INSTANCE_ID
    remoteRef:
      property: username
      key: username_password/6eb1d144-4a5b-0441-dc83-ea17b46a446f
  - secretKey: WATSONX_APIKEY
    remoteRef:
      property: password
      key: username_password/6eb1d144-4a5b-0441-dc83-ea17b46a446f