apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: backend
  name: backend-cm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  COLLECTIONDB_HOST: postgres
  COLLECTIONDB_PORT: "5432"

  CHUNK_OVERLAP: "100"
  CHUNKING_STRATEGY: fixed
  MAX_CHUNK_SIZE: "1000"
  MAX_NEW_TOKENS: "500"
  MIN_CHUNK_SIZE: "100"
  MIN_NEW_TOKENS: "200"
  RAG_LLM: meta-llama/llama-3-70b-instruct
  RANDOM_SEED: "50"
  SEMANTIC_THRESHOLD: "0.5"
  TEMPERATURE: "0.7"
  TOKENIZER: meta-llama/llama-3-70b-instruct
  TOKENIZER_MODEL: google/flan-t5-xl
  TOP_K: "5"
  UPSERT_BATCH_SIZE: "100"
  
  WATSONX_URL: https://us-south.ml.cloud.ibm.com
  EMBEDDING_DIM: "384"
  EMBEDDING_FIELD: embedding
  EMBEDDING_MODEL: sentence-transformers/all-minilm-l6-v2

  FILE_STORAGE_PATH: /mnt/data