apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-oidc-external-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: ibmcloud-secrets-store
    kind: ClusterSecretStore
  target:
    name: backend-oidc-secret
  data:
  - secretKey: ibm-client-id
    remoteRef:
      property: username
      key: username_password/0abc3959-b4df-de49-e196-33590972fb90
  - secretKey: ibm-client-secret
    remoteRef:
      property: password
      key: username_password/0abc3959-b4df-de49-e196-33590972fb90