apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-configmap.yaml
  - backend-oidc-configmap.yaml
  - backend-oidc-externalsecret.yaml
  - backend-jwt-externalsecret.yaml
  - backend-watsonx-externalsecret.yaml
  - backend-data-persistentvolumeclaim.yaml
  - backend-deployment.yaml
  - backend-service.yaml