apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-modulo

resources:
  - namespace.yaml
  - ../../base

components:
  - ../../components/milvus

patches:
  - path: patches/backend-configmap-patch.yaml