apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-modulo

resources:
  - namespace.yaml
  - ../../base

components:
  - ../../components/milvus

configMapGenerator:
  - name: backend-cm
    behavior: merge
    literals:
      - VECTOR_DB=milvus
      - MILVUS_HOST=milvus-standalone
      - MILVUS_INDEX_PARAMS=""
      - MILVUS_PORT=19530
      - MILVUS_SEARCH_PARAMS=""