apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - etcd-data-persistentvolumeclaim.yaml
  - etcd-deployment.yaml
  - etcd-service.yaml 
  - minio-externalsecret.yaml
  - minio-data-persistentvolumeclaim.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - milvus-data-persistentvolumeclaim.yaml
  - milvus-standalone-deployment.yaml
  - milvus-standalone-service.yaml