apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: milvus-standalone
  name: milvus-standalone
spec:
  ports:
    - port: 19530
  selector:
    app: milvus-standalone
