apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: milvus
  name: milvus-data
spec:
  storageClassName: ibmc-vpc-block-10iops-tier
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
