apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-external-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: minio
spec:
  secretStoreRef:
    name: ibmcloud-secrets-store
    kind: ClusterSecretStore
  target:
    name: minio-secret
  data:
  - secretKey: accessKey
    remoteRef:
      property: username
      key: username_password/9ac1eed7-3c5c-c95a-6094-f009a9658e2c
  - secretKey: secretKey
    remoteRef:
      property: password
      key: username_password/9ac1eed7-3c5c-c95a-6094-f009a9658e2c