apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./postgres
  - ./backend
  - ./frontend

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: ca.icr.io/rag-modulo/backend:1.0.5
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: ca.icr.io/rag-modulo/frontend:1.0.5
    target:
      kind: Deployment
      name: frontend