apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: postgres

resources:
  - postgres-externalsecret.yaml
  - postgres-cm.yaml
  - postgres-data-persistentvolumeclaim.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml