apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: ibmcloud-secrets-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
  - secretKey: username
    remoteRef:
      property: username
      key: username_password/f3d44e84-15fd-05b7-1980-97e833d6e4e2
  - secretKey: password
    remoteRef:
      property: password
      key: username_password/f3d44e84-15fd-05b7-1980-97e833d6e4e2